######################################################################
# Automatically generated by qmake (2.01a) ? 6? 30 10:11:04 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Matrix.h tnGLWidget.h tnWindow.h Utility.h Vector.h
SOURCES += main.cpp \
           Matrix.cpp \
           tnGLWidget.cpp \
           tnWindow.cpp \
           Utility.cpp \
           Vector.cpp
